mod 'puppet-nginx', '3.0.0'
mod 'puppetlabs-concat', '7.0.0'
mod 'puppetlabs-stdlib', '7.0.0'
mod 'puppetlabs-translate', '2.2.0'
mod 'gutocarvalho-puppetagent', '1.4.0'
mod 'samuelson/dockeragent'
mod 'puppetlabs/docker'
